// This file was generated by the XState CLI, please do not edit it manually.
import { createMachine } from 'xstate';

const machine = createMachine(
  {
    context: {
      timer: 0,
    },
    id: 'Traffic Light',
    initial: 'green',
    states: {
      green: {
        description: 'The light is green. Cars can proceed safely.',
        on: {
          'Change to yellow': {
            target: 'yellow',
          },
        },
      },
      yellow: {
        description: 'The light is yellow. Cars should prepare to stop.',
        on: {
          'Change to red': {
            target: 'red',
          },
        },
      },
      red: {
        description: 'The light is red. Cars should stop.',
        on: {
          'Change to green': {
            target: 'green',
          },
        },
      },
    },
    types: {
      events: {} as
        | { type: 'Change to red' }
        | { type: 'Change to green' }
        | { type: 'Change to yellow' },
      context: {} as { timer: number },
    },
  },
  {
    actions: {},
    actors: {},
    guards: {},
    delays: {},
  }
);
export const skyConfig = {
  actorId: '461ab995-e697-4069-b807-16f3a19607b1',
  machine,
};
