// This file was generated by the XState CLI, please do not edit it manually.
import { assign, createMachine } from 'xstate';

export const machine = createMachine(
  {
    context: {
      timer: 1000,
      color: 'green',
    },

    on: {
      'light clicked': {
        actions: assign(({ context, event }) => {
          const color = getColorForPosition(event.lightPosition);
          return {
            color,
          };
        }),
      },
    },

    id: 'Traffic Light Machine',
    initial: 'Green',
    states: {
      Green: {
        on: {
          'timer elapsed': 'Yellow',
          lightSelected: {},
        },
        after: {
          'light-timer': 'Yellow',
        },
      },

      Yellow: {
        on: {
          'timer elapsed': 'Red',
        },
        after: {
          'light-timer': 'Red',
        },
      },

      Red: {
        on: {
          'timer elapsed': 'Green',
        },
        after: {
          'light-timer': 'Green',
        },
      },
    },
  },
  {
    delays: {
      'light-timer': 10000000,
    },
  }
);

const getColorForPosition = (lightPosition) => {
  console.log({ lightPosition });
  switch (lightPosition) {
    case 'top':
      return 'red';
    case 'middle':
      return 'yellow';
    case 'bottom':
      return 'green';
  }
};
