// This file was generated by the XState CLI, please do not edit it manually.
import { createMachine } from 'xstate';

export const machine = createMachine(
  {
    context: {
      timer: 1000,
    },

    // on: {
    //     'change timer': {
    //       actions: 'setTimer',

    //     }
    // }

    id: 'Traffic Light Machine',
    initial: 'Green',
    states: {
      Green: {
        on: {
          'timer elapsed': 'Yellow',
        },
        after: {
          'light-timer': 'Yellow',
        },
      },

      Yellow: {
        on: {
          'timer elapsed': 'Red',
        },
        after: {
          'light-timer': 'Red',
        },
      },

      Red: {
        on: {
          'timer elapsed': 'Green',
        },
        after: {
          'light-timer': 'Green',
        },
      },
    },
  },
  {
    delays: {
      'light-timer': 500,
      //   'light-timer': ({ context }) => context.timer,
    },
  }
);
