// This file was generated by the XState CLI, please do not edit it manually.
import { assign, createMachine } from 'xstate';

const machine = createMachine(
  {
    /** @xstate-layout N4IgpgJg5mDOIC5QHECuBbARgQwDa4AIBZbAYwAsBLAOzADoBJCXMAYgFVYwAnAh6rtwAusAgGEA9jQDaABgC6iUAAcJsSkMoTqSkAA9EARgBMAVjoA2UwA5rFgMz2ALMcOzXpgDQgAnomuGdPbGxgCchtbOhoZO9qGhAL4J3mhYeIQkFDT0TCwEAOoa5OJS1HxlAMq4EkIcggQAKqjcAuLc2NQA1nKKSCCq6praugYIpoYA7HSRjs72DqET7t5+CAFBIeHGAVYT86ZJKRg4+MRkVLR0AArcYAQ3EqRw6tRQBAAiYAMakCU0rJIaAQKqhSE9YLAAGaofA+D5fNQ-CA9XTfIY6PqjUxOax0eIhCyhOyhCyGCwWFaIOJTOKyBwmWShWSmUzGQ4gVInDLnbJ0BrcShQGC8TnpAgAJTALGwXFYotOkulXAgfHQ6EglGwQilPhRfTRWgxoFGZOMeNMSwmEyspkclLGplkdBipgsE3C9kdC3Z8u5WUuvoIADF0jQ3kJyNwJKgoMVyFLKHoCEJUJg4Nco+CXm9+dgAFZgUhCCTcHysTSkboKVGI9EjRCye2yH3HMWZC70K64bA+HiNZrURjMNgAQWo1Gj1CeBGU3d7vDTuEoYAAbnACFyCJRREDSCXbkWZ7XDXqVMfhpjEABaayLPFuYwTJysx3uUL2twWOjGKxOCy2exJgiWwWzSU5215Lsez7JoWiHFhWDHCdUCnO5Z2ghcE1XddN23Lcyj3bgDyEI9BhPQxejPMiL2Na9rAtOhZAiQC7CYolDHtcx3CccIWVJQxggtexQM3CDLig+d+zgsRyA6KAw3uOcYIHAFZNeO4JOUlpT36c8jX0a9ogEugJhsQxQliC0lnsax7Ufexv1kJ8YjCJ8SSSZIQAnCA4F0QMxLAGtqP00YrwZUITLMizPStWQbPtMKn0sZ9rBCNiLCciwRLbHlLlyQL9T0+sEBce11h42RrCtd0cWtCY2U8-zcpyYcCiKP4yn4YFqiEIKNENYrAIcpxzO2CZ6KJcZjCcMrAgqqrPzi+w4sSRrW3A5qMw0zNngUz40V+QF9INGiDLGCZ7WcM0YmsJwnCc28-zdbKNv9eh+UFYUCEDRUwBlAqqP606sXJZ0STi1KLIsEJbN8RBsQigJ5j-WQnOxdwXr9Ds6EDEN8AUiMoxjOMEyTFM03gQrguKsKnCmCYBOcK0MtiJiLrhhAbxpTZJgCerecxs43px9bCDxpdXmTSNo1jAh4yXMnU3TB4swU3MCyLEtVkButL05+ITMZunrVkVnJntUyIos21sRxQwbAZwWAuuJTeFg46ir1sKyUCUyAmiqyIYS1LvyJVHKosWJBKdzbNLdgd4IB3Tqa9twWTxBnM8q207opDn7CmU3HAidxxhMVajjArHINdqTBxkuSFLjuu+t12jOfowJoetVlwniJ92dWH8vzCRxTFCYxmXJYxhLWquhex-JZJIsV0PnURSA6AgIAkAgtT305NHVURCZl8hoxIiM7igbB1QIAAKZBqhOb7b7uABRNdqBEABKVuBtTvbcwVVXDTVsIsMu9p7pOEsDZAScVGR03CDHYWS996r1dhvLeO894r0PpQY+UsiaxgvlLa+b8H5PwkC-ZAFDP5gG-rAH+dAiDPGwDAe4UZ-7A0Mm4KYICTA4lvKZaIUDwjOkfISGwqMHD1Q8gkIAA */
    context: {
      timer: 0,
      timeDeltaMs: 100,
      numberOfReportsPerTurn: 5,
      reportsInThisTurn: 0,
      machine: {
        /*assume straight pipe for now, helix later*/ heightMeters: 10,
      },
      gumball: {
        // meters
        velocity: 0,
        distanceFallen: 0,
      },
    },
    id: 'Gumball Machine',
    states: {
      Idle: {
        on: {
          'User Inserts Coin': 'Idle With Coin In Slot',
        },
      },

      'Idle With Coin In Slot': {
        on: {
          'User Turns Crank': 'Pre Processing Deposited Coin',
        },
      },

      'Pre Processing Deposited Coin': {
        description: `Happens after the coin is sent through the crank into the machine but immediately prior to being successfully deposited. 

Problems that could occur here are the coin receptical down
 in the machine is jammed, the coin could be determined to be counterfeit, etc.`,

        on: {
          'Coin Successfully Deposited': 'Trigger Gumball Release',
        },
      },

      'Trigger Gumball Release': {
        on: {
          'Gumball Released Immediately': 'Gumball Falling through helix tubes',
        },
      },

      'Gumball Falling through helix tubes': {
        states: {
          'Processing Trajectory': {
            entry: [
              (ctx, evt) => {
                console.log(ctx, evt);
                const {
                  timeDeltaMs,
                  gumball: { velocity, distanceFallen },
                } = ctx;
                const acc_g = 9.8; /*m/s*/

                const newDistanceFallen =
                  distanceFallen + velocity * (timeDeltaMs / 1000);
                const newVelocity = velocity + (acc_g * timeDeltaMs) / 1000;

                const newGumball = {
                  velocity: newVelocity,
                  distanceFallen: newDistanceFallen,
                };

                // Let's just start really simply by adding acc_g to velocity
                return assign({
                  gumball: newGumball,
                });
              },
            ],

            on: {
              tick: {
                target: 'Processing Trajectory',
              },
            },

            // after: {
            //   1000: { target: 'Processing Trajectory' },
            // },
          },
        },

        initial: 'Processing Trajectory',
      },

      'Player Turn': {
        states: {
          Idle: {
            on: {
              'Announce player believes ball is in correct position': [
                {
                  cond: 'ifNotPlayerturnAnymore',
                  target: 'Changing Player Turn',
                },
                {
                  target: 'Idle',
                  action: 'decrementRemainingReports',
                },
              ],
            },
          },

          'Changing Player Turn': {
            on: {
              'Change Player Turn': 'Idle',
            },
          },
        },

        initial: 'Idle',
      },

      'What all players can do at all times throughout the game (Global Game Events)':
        {
          states: {
            'Message Pro': {},
          },

          initial: 'Message Pro',
        },
    },
    types: {
      events: {} as
        | { type: 'Change to red' }
        | { type: 'Change to green' }
        | { type: 'tick' }
        | { type: 'Report' }
        | { type: 'Change to yellow' },

      context: {} as {
        timer: number;
        timeDeltaMs: number;
        players: [string, string];
        currentPlayer: 1 | 2;
        numberOfReportsPerTurn: number;
        reportsInThisTurn: number;
        machine: number;

        heightMeters: number;
        gumball: { velocity: number; distanceFallen: number };
      },
    },
    type: 'parallel',
  },
  {
    actions: {
      decrementRemainingReports: (ctx, event) => {
        // TODO: do something with ctx and event
        return ctx;
      },
    },
    actors: {},
    guards: {
      ifNotPlayerturnAnymore: (ctx, event) => {
        // TODO: do something with ctx and event
        return false;
      },
    },
    delays: {},
  }
);
